// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using imasderol.infrastructure;

#nullable disable

namespace imasderol.infrastructure.Migrations
{
    [DbContext(typeof(ImasderolDbContext))]
    [Migration("20240125184752_Weapon Added")]
    partial class WeaponAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("imasderol.infrastructure.zombicide.skill.SkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("imasderol.infrastructure.zombicide.skill.WeaponAttackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("AmmunitionType")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("MaximumRange")
                        .HasColumnType("int");

                    b.Property<int>("MinimumRange")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDice")
                        .HasColumnType("int");

                    b.Property<bool>("Silent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("WeaponEntityId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WeaponEntityId");

                    b.ToTable("WeaponAttackEntity");
                });

            modelBuilder.Entity("imasderol.infrastructure.zombicide.skill.WeaponEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("AmmoType")
                        .HasColumnType("int");

                    b.Property<bool>("DuaWield")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("OpensDoors")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OpensDoorsSilently")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("imasderol.infrastructure.zombicide.skill.WeaponAttackEntity", b =>
                {
                    b.HasOne("imasderol.infrastructure.zombicide.skill.WeaponEntity", null)
                        .WithMany("Attacks")
                        .HasForeignKey("WeaponEntityId");
                });

            modelBuilder.Entity("imasderol.infrastructure.zombicide.skill.WeaponEntity", b =>
                {
                    b.Navigation("Attacks");
                });
#pragma warning restore 612, 618
        }
    }
}
